### ISSUE TITLE
Keycloak integration is broken

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#87]
After the Login button is clicked, It ends up redirecting to http://localhost:8088/wizard/launchpad-new-project/1#state=e782e21f-5554-48e6-8f39-b4334ece41bc&code=VkFsVo4AhdCpV8dani6hhE5wdsh9dtwjCrExVc15HuU.593440fe-e68d-4f8c-b54f-ff41dcf87cbd and the following error is seen in the console: 

```
An error occurred TypeError: Cannot read property 'postMessage' of null
    at checkLoginIframe (eval at 1056 (http://localhost:8088/app.js:110:1), <anonymous>:875:53)
    at Keycloak.kc.updateToken (eval at 1056 (http://localhost:8088/app.js:110:1), <anonymous>:458:37)
    at eval (eval at 112 (http://localhost:8088/app.js:127:1), <anonymous>:60:22)
    at new ZoneAwarePromise (eval at <anonymous> (http://localhost:8088/polyfills.js:2957:1), <anonymous>:518:29)
    at KeycloakService.getToken (eval at 112 (http://localhost:8088/app.js:127:1), <anonymous>:57:16)
    at KeycloakHttp.request (eval at 1043 (http://localhost:8088/app.js:63:1), <anonymous>:38:50)
    at KeycloakHttp.Http.get (eval at <anonymous> (http://localhost:8088/vendor.js:1935:1), <anonymous>:139:21)
```

**Comment by gastaldi** [comment]
Fixed by disabling the Keycloak iframe
